#### Web Scrapping

In [1]:
import scrapy

In [10]:
import scrapy

class ForumSpider(scrapy.Spider):
    name = "posts"
    topic = "vidatni-lvivjani.69"
    base_url = 'http://http://forum.lvivport.com/forums'
    start_urls = ['{}/{}/'.format(base_url, topic)]

In [14]:
import urllib.parse
topic = "vidatni-lvivjani.69"
base_url = 'http://forum.lvivport.com/forums/'
urllib.parse.urljoin(base_url, topic)

'http://forum.lvivport.com/forums/vidatni-lvivjani.69'

In [1]:
import re

In [106]:
s = """| СИНОНИМИ = [[rt]]
| СРОДНИ ДУМИ = [[конфронтирам]]
| ПРОИЗВОДНИ ДУМИ = 
| ДРУГИ = """

In [107]:
patt = r"(?:СИНОНИМИ =\s+([^|]*))"
match = re.search(patt, s, re.M)
raw_syn = match.group(1)
re.findall(r"\[\[(.*?)\]\]", raw_syn, re.M)

['rt']

In [58]:
from SPARQLWrapper import SPARQLWrapper, TSV, CSV

sparql = SPARQLWrapper("http://dbpedia.org/sparql")
query = """
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>

SELECT count(*)
WHERE
{
   ?person a dbo:Person .
}

"""
sparql.setQuery(query)
sparql.setReturnFormat(CSV)
results = sparql.query().convert()

In [61]:
import warc

In [64]:
import urllib.parse

In [70]:
p = urllib.parse.urlparse("http://012122.net/www_012122_com/www_41235_com_wangyouduizhi19Ezanbujuekoujiehezhongguozhishengji60_513.html")

In [71]:
p.netloc

'012122.net'

In [109]:
import pandas as pd

In [111]:
path = "/home/karimlulu/Documents/checklist_stat.txt"
df = pd.read_csv(path)

In [112]:
df

               name  state  item_gender  count
0      A-Line Skirt      1          139   1552
1      A-Line Skirt      2          139   1168
2      A-Line Skirt      3          139   1410
3       Ankle Boots      1          139    588
4       Ankle Boots      2          139    838
5       Ankle Boots      3          139    261
6      Ballet Flats      1          139    970
7      Ballet Flats      2          139   2769
8      Ballet Flats      3          139    679
9       Belted Coat      1          139   1524
10      Belted Coat      2          139   1611
11      Belted Coat      3          139   1392
12           Blazer      1          139   1533
13           Blazer      2          139   2712
14           Blazer      3          139   1420
15           Blouse      1          139     90
16           Blouse      2          139    297
17           Blouse      3          139     89
18           Bomber      1          139     79
19           Bomber      2          139    100
20           Bomber      3          139     65
21    Bomber Jacket      1            1      7
22    Bomber Jacket      2            1      6
23    Bomber Jacket      3            1     10
24         Bracelet      1          139     82
25         Bracelet      2          139   3199
26         Bracelet      3          139      1
27          Brogues      1            1    282
28          Brogues      1          139     23
29          Brogues      2            1    153
..              ...    ...          ...    ...
363          V-Neck      1            1    407
364          V-Neck      2            1    720
365          V-Neck      3            1    437
366     V-Neck Knit      1          139   1376
367     V-Neck Knit      2          139   1434
368     V-Neck Knit      3          139    986
369      V-Neck Tee      1            1    205
370      V-Neck Tee      1          139    856
371      V-Neck Tee      2            1    542
372      V-Neck Tee      2          139   3106
373      V-Neck Tee      3            1    219
374      V-Neck Tee      3          139    402
375            Vest      1          139      2
376            Vest      2          139      1
377            Vest      3          139      1
378      Waist Belt      1          139    953
379      Waist Belt      2          139   2431
380      Waist Belt      3          139    863
381       Weekender      1            1    240
382       Weekender      2            1    203
383       Weekender      3            1    255
384  Wide Leg Pants      1          139    932
385  Wide Leg Pants      2          139   1454
386  Wide Leg Pants      3          139   1990
387      Wrap Scarf      1          139    591
388      Wrap Scarf      2          139   1159
389      Wrap Scarf      3          139    491
390   Zip-Up Hoodie      1            1      6
391   Zip-Up Hoodie      2            1      9
392   Zip-Up Hoodie      3            1      6

[393 rows x 4 columns]

In [118]:
mapp = {1: 'Need it',
        2: 'Have it',
        3: 'Not for me'}
g_map = {1:"man", 139:"woman"}

In [116]:
df["state"] = df["state"].map(lambda x: mapp.get(x, x))

In [119]:
df["item_gender"] = df["item_gender"].map(lambda x : g_map.get(x, x))

In [133]:
df.head()

           name       state item_gender  count
0  A-Line Skirt     Need it       woman   1552
1  A-Line Skirt     Have it       woman   1168
2  A-Line Skirt  Not for me       woman   1410
3   Ankle Boots     Need it       woman    588
4   Ankle Boots     Have it       woman    838

In [146]:
pct = pd.pivot_table(df, index=["name", "item_gender"], columns="state", values=["count"]).reset_index()
print(pct.head())
pct.columns = pct.columns.droplevel()

               name item_gender   count
state                           Have it Need it Not for me
0      A-Line Skirt       woman  1168.0  1552.0     1410.0
1       Ankle Boots       woman   838.0   588.0      261.0
2      Ballet Flats       woman  2769.0   970.0      679.0
3       Belted Coat       woman  1611.0  1524.0     1392.0
4            Blazer       woman  2712.0  1533.0     1420.0

In [145]:
pct

state                               Have it  Need it  Not for me
0              A-Line Skirt  woman   1168.0   1552.0      1410.0
1               Ankle Boots  woman    838.0    588.0       261.0
2              Ballet Flats  woman   2769.0    970.0       679.0
3               Belted Coat  woman   1611.0   1524.0      1392.0
4                    Blazer  woman   2712.0   1533.0      1420.0
5                    Blouse  woman    297.0     90.0        89.0
6                    Bomber  woman    100.0     79.0        65.0
7             Bomber Jacket    man      6.0      7.0        10.0
8                  Bracelet  woman   3199.0     82.0         1.0
9                   Brogues    man    153.0    282.0       324.0
10                  Brogues  woman      5.0     23.0        16.0
11              Button-Down  woman   2598.0    177.0        56.0
12                 Cardigan    man    404.0    453.0       542.0
13             Casual Pants    man      3.0      2.0         4.0
14          Chain Strap Bag  woman     10.0     10.0         4.0
15           Chambray Shirt    man    313.0    330.0       301.0
16            Checked Shirt    man    521.0    240.0       183.0
17            Chelsea Boots    man    129.0    277.0       324.0
18            Chelsea Boots  woman    964.0    672.0       570.0
19                   Chinos    man    638.0    280.0       255.0
20           Chunky Sweater  woman   2937.0   1186.0      1024.0
21              Classic Tie    man    660.0     46.0         NaN
22                Crew Neck    man    828.0    222.0        85.0
23     Crew Neck Sweatshirt    man    620.0     75.0        59.0
24            Crew Neck Tee    man   1125.0    182.0       102.0
25           Crew-Neck Knit  woman   2259.0    160.0       108.0
26            Crew-Neck Tee  woman   4043.0    936.0       681.0
27            Cropped Jeans  woman      1.0      NaN         NaN
28            Cropped Pants  woman   3002.0    977.0       898.0
29           Cross Body Bag  woman   2127.0    974.0       676.0
..                      ...    ...      ...      ...         ...
107          Slim-Fit Shirt    man    968.0     49.0         NaN
108              Sport Coat    man    764.0    522.0       455.0
109      Statement Necklace  woman   2110.0   1131.0       600.0
110         Statement Pumps  woman   1835.0   1155.0      1265.0
111         Statement Skirt  woman      8.0      4.0         7.0
112          Straight Jeans    man   1171.0    138.0       112.0
113          Straight Jeans  woman   4424.0    702.0       873.0
114      Straight Leg Pants  woman     43.0      9.0        13.0
115             Striped Tee  woman      1.0      2.0         NaN
116             Striped Top  woman   2334.0   1161.0       960.0
117          Structured Bag  woman   2283.0   1103.0       886.0
118             Suit Jacket    man    737.0    302.0       246.0
119                 Sweater    man    616.0    256.0       213.0
120              Sweatshirt  woman   3775.0    727.0       403.0
121                Tank Top  woman    170.0     16.0        28.0
122                  Tights  woman   2538.0    941.0       374.0
123             Trench Coat    man    146.0    335.0       374.0
124             Trench Coat  woman   1134.0   1631.0      1256.0
125              Turtleneck    man     27.0     38.0        53.0
126     Turtleneck Knitwear  woman   1696.0    235.0       401.0
127                  V-Neck    man    720.0    407.0       437.0
128             V-Neck Knit  woman   1434.0   1376.0       986.0
129              V-Neck Tee    man    542.0    205.0       219.0
130              V-Neck Tee  woman   3106.0    856.0       402.0
131                    Vest  woman      1.0      2.0         1.0
132              Waist Belt  woman   2431.0    953.0       863.0
133               Weekender    man    203.0    240.0       255.0
134          Wide Leg Pants  woman   1454.0    932.0      1990.0
135              Wrap Scarf  woman   1159.0    591.0       491.0
136           Zip-Up Hoodie    man      9.0      6.0         6.0

[137 rows x 5 columns]

In [147]:
pct.to_excel("/home/karimlulu/Documents/checklist_stat_gender.xlsx")